---
- name:
    Provision the server, install build tools and dependencies
    like unzip and virtualbox.
  hosts: metal
  tasks:
    - name: Install missing unzip package
      apt:
        name: unzip
        update_cache: yes
      register: _task
      retries: 3
      delay: 5
      until: _task is succeeded
    - name: Run install_virtualbox.sh
      script: "{{ playbook_dir }}/bin/install_virtualbox.sh"
